apiVersion: v2
name: kube-prometheus-stack
description: Wrapper chart for kube-prometheus-stack with templated values
type: application
version: 1.0.0
appVersion: "79.10.0"

dependencies:
  - name: kube-prometheus-stack
    version: "79.10.0"
    repository: https://prometheus-community.github.io/helm-charts
