apiVersion: v2
name: example-service
description: Example service Helm chart
type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: example-library
    version: "0.1.0"
    repository: file://../../_library
    alias: library
