# =============================================================================
# DEV ENVIRONMENT OVERRIDES
# =============================================================================
replicaCount: 1

extraEnv:
  - name: LOG_LEVEL
    value: "debug"
