apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-cookie
  namespace: oauth2-proxy
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-shared
  target:
    name: oauth2-proxy-cookie
    creationPolicy: Owner
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: OAUTH2_PROXY_COOKIE_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-redis
  namespace: oauth2-proxy
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-shared
  target:
    name: oauth2-proxy-redis
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: OAUTH2_PROXY_REDIS_PASSWORD
