apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-shared
  target:
    name: tailscale-oauth
    creationPolicy: Owner
    template:
      data:
        client_id: {{ .Values.global.tailscale.clientId | quote }}
        client_secret: "{{`{{ .clientSecret }}`}}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: TS_OAUTH_CLIENT_SECRET
