{{- if and .Values.auth.enabled .Values.auth.key }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "redis-instance.fullname" . }}-es
  labels:
    {{- include "redis-instance.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.auth.secretStore }}
  target:
    name: {{ include "redis-instance.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.auth.secretKey }}
      remoteRef:
        key: {{ .Values.auth.key }}
{{- end }}
